openapi: 3.0.3
info:
  title: DevNest Portal API (OpenAPI 3.0)
  description: The DevNest Portal API endpoints definitions based on the OpenAPI 3.0
    specification.
  termsOfService: https://devnest.ro/terms-and-conditions
  contact:
    email: contact@devnest.ro
  version: 1.0.0
servers:
- url: https://me.devnest.ro/api/v1
tags:
- name: Timesheets
  description: Timesheets
- name: Projects
  description: Projects
- name: Employees
  description: Employees
- name: Allocations
  description: Allocations
- name: Feedback
  description: Feedback
- name: Settings
  description: Settings
paths:
  /timesheets:
    get:
      tags:
      - Timesheets
      summary: Returns all timesheets
      description: Returns all timesheets
      operationId: getAllTimesheets
  /timesheets/{timesheetId}:
    get:
      tags:
      - Timesheets
      summary: Returns timesheet by timesheetId
      description: Return timesheet by timesheetId
      operationId: getTimesheetById
    put:
      tags:
      - Timesheets
      summary: Update an timesheet
      description: Update an timesheet
  /timesheets/project-status/{projectId}:
    get:
      tags:
      - Timesheets
      summary: Returns project-status from timesheet by projectId
      description: Returns project-status from timesheet by projectId
      operationId: getProjectStatusByProjectId
  /timesheets/project-status/{projectId}/{year}/{month}:
    get:
      tags:
      - Timesheets
      summary: Get the status of a project's timesheets for a specific year and month.
      description: Retrieve the status of a project's timesheets for a specific year
        and month.
      security:
      - devnest_auth:
        - read:timesheets
  /monthlyTimesheet/{employeeId}:
    put:
      tags:
      - Timesheets
      summary: Update Timesheet
      description: Updates the timesheet for the specified employee.
  /projects:
    get:
      tags:
      - Projects
      summary: Get all projects
      description: Returns an array of all project objects like in /responseBodies/Project.
      operationId: getAllProjects
    post:
      tags:
      - Projects
      summary: Create a new project
      description: "Adds a new project having all the submitted properties. It will\
        \ return the newly created project, having the id besides the submitted properties."
      operationId: createProject
  /projects/{projectId}:
    get:
      tags:
      - Projects
      summary: Returns the project by projectId
      description: Returns a project like in /responsesBodies/Project by projectId.
    put:
      tags:
      - Projects
      summary: Returns updated project by projectId
      description: Return a project like in /responsesBodies/Project by projectId
        by submitting a JSON file in request body like in /responsesBodies/Project.
    delete:
      tags:
      - Projects
      summary: Delete a project by id
      description: Delete the project by projectId.
    patch:
      tags:
      - Projects
      summary: Update the 'status' parameter based on whether the project is archived
        or not.
      description: Update the 'status' parameter based on whether the project is archived
        or not.
  /projects/{projectId}/allocations:
    get:
      tags:
      - Allocations
      summary: Get all allocations by projectId
      description: "This endpoint with GET method, return an array of all allocation\
        \ objects like in /responseBodies/Allocation by projectId with 200 Succsefully\
        \ status or 5xx status if it's necessary"
      operationId: getAllAllocationsById
    put:
      tags:
      - Allocations
      summary: Update allocations
      description: "This endpoint with PUT method, update allocations by submitting\
        \ a JSON file in request body.This file should include an array of data about\
        \ allocation like in /requestBodies/Allocation. IMPORTANT, if one of allocations\
        \ is invalid, then none of allocations will be updated."
      operationId: updateAllocations
    post:
      tags:
      - Allocations
      summary: Create new allocations
      description: "This endpoint with POST method, create new allocations by submitting\
        \ a JSON file in request body.This file should include an array of data about\
        \ allocation like in /requestBodies/Allocation.Upon successful creation of\
        \ all allocations, the endpoint will return a 201 Created status code along\
        \ with the array of newly created allocations object in the response body\
        \ like in /responseBodies/Allocation. There can be errors like validation(400\
        \ Bad request), not found project by projectId(404 Not found) or server error(5xx).\
        \ IMPORTANT, if one of allocations is invalid, then none of allocations will\
        \ be created."
      operationId: createAllocations
  /projects/{projectId}/allocations/{employeeId}:
    put:
      tags:
      - Allocations
      summary: Update allocation by projectId and employeeId
      description: "This endpoint with PUT method, update allocations by submitting\
        \ a JSON file in request body.This file should a data about allocation like\
        \ in /schemas/CreatedAllocation."
      operationId: updateAllocation
  /projects/{projectId}/allocations/{allocationId}:
    delete:
      tags:
      - Allocations
      summary: Delete allocation by allocationId from project by projectId
      description: "DELETE method will delete allocation by allocationId and projectId\
        \ and will return 200 Succsefully status if was deleted, or error responses\
        \ (400(for invalid allocationId or projectId), 404(not found allocation by\
        \ allocationId and projectId), 5xx(server error))"
  /projects/{projectId}/history:
    get:
      tags:
      - Projects
      summary: Get history for a project
      description: Get history for a project
      operationId: getHistoryForProject
      security:
      - devnest_auth:
        - read:history
  /employees:
    get:
      tags:
      - Employees
      summary: Get all employees
      description: Get all employees
      operationId: getAllEmployees
      security:
      - devnest_auth:
        - read:employees
    post:
      tags:
      - Employees
      summary: Create a new employee in the database
      description: Create a new employee in the database
      security:
      - devnest_auth:
        - write:employees
  /employees/{employeeId}:
    get:
      tags:
      - Employees
      summary: Get employee by Id
      description: Get employee by Id
      operationId: getEmployeeById
      security:
      - devnest_auth:
        - read:employees
    put:
      tags:
      - Employees
      summary: Update an employee
      description: Update an employee
      security:
      - devnest_auth:
        - write:employees
    delete:
      tags:
      - Employees
      summary: Deletes an existing employee
      description: Delete an existing employee by id
      operationId: deleteEmployeeById
      security:
      - devnest_auth:
        - write:employees
    patch:
      tags:
      - Employees
      summary: Update the 'status' parameter based on whether the employee is archived
        or not.
      description: Update the 'status' parameter based on whether the employee is
        archived or not.
      security:
      - devnest_auth:
        - write:employees
  /employees/{employeeId}/password:
    put:
      tags:
      - Employees
      summary: Update employee password
      description: Update the password for a specific employee
      security:
      - devnest_auth:
        - write:employees
  /employees/{employeeId}/history:
    get:
      tags:
      - Employees
      summary: Get history for an employee
      description: Get history for an employee
      operationId: getHistoryForEmployee
      security:
      - devnest_auth:
        - read:history
  /employees/{employeeId}/allocations:
    get:
      tags:
      - Allocations
      summary: Get allocations for an employee
      description: Get allocations for an employee
      operationId: getAllocationsForEmployee
      security:
      - devnest_auth:
        - read:allocations
    post:
      tags:
      - Allocations
      summary: Create a new allocation for an employee
      description: Create a new allocation for an employee
      operationId: createAllocationForEmployee
      security:
      - devnest_auth:
        - write:allocations
  /employees/{employeeId}/allocations/{allocationId}:
    get:
      tags:
      - Allocations
      summary: Get an allocation for a specific employee
      description: Get an allocation for a specific employee
      operationId: getAllocationForEmployee
      security:
      - devnest_auth:
        - read:allocations
    put:
      tags:
      - Allocations
      summary: Update an allocation for a specific employee
      description: Update an allocation for a specific employee
      operationId: updateAllocationForEmployee
      security:
      - devnest_auth:
        - write:allocations
    delete:
      tags:
      - Allocations
      summary: Delete an allocation for a specific employee
      description: Delete an allocation for a specific employee
      operationId: deleteAllocationForEmployee
      security:
      - devnest_auth:
        - write:allocations
  /feedback:
    get:
      tags:
      - Feedback
      summary: Get all feedback
      description: Get all feedback
      operationId: getAllFeedback
      security:
      - devnest_auth:
        - read:feedback
  /feedback/{employeeId}:
    get:
      tags:
      - Feedback
      summary: Get overall feedback for an employee
      description: Get overall feedback for an employee
      operationId: getEmployeeOverallFeedback
      security:
      - devnest_auth:
        - read:feedback
  /feedback/{employeeId}/month:
    get:
      tags:
      - Feedback
      summary: Get all monthly feedback for an employee
      description: Get all monthly feedback for an employee
      operationId: getEmployeeMonthlyFeedback
      security:
      - devnest_auth:
        - read:feedback
    post:
      tags:
      - Feedback
      summary: Create feedback for a specific employee in a specific month
      description: Create feedback for a specific employee in a specific month
      security:
      - devnest_auth:
        - write:feedback
  /feedback/{employeeId}/month/{feedbackId}:
    get:
      tags:
      - Feedback
      summary: Return one feedback for an employee
      description: Return one feedback for an employee for a given month
      operationId: getEmployeeFeedback
      security:
      - devnest_auth:
        - read:feedback
  /archives/employees:
    get:
      tags:
      - Archives
      summary: Get all archived employees
      description: Get all archived employees
      operationId: getAllArchivedEmployees
      security:
      - devnest_auth:
        - read:archives
  /archives/projects:
    get:
      tags:
      - Archives
      summary: Get all archived projects
      description: Get all archived projects
      operationId: getAllArchivedProjects
      security:
      - devnest_auth:
        - read:archives
  /settings:
    get:
      tags:
      - Settings
      summary: Get all settings
      description: Get all settings
      operationId: getAllSettings
      security:
      - devnest_auth:
        - read:settings
    put:
      tags:
      - Settings
      summary: Update settings
      description: Update settings
      operationId: updateSettings
      security:
      - devnest_auth:
        - write:settings
components:
  securitySchemes:
    devnest_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://me.devnest.ro/oauth/auth
          scopes:
            read:timesheets: Read timesheets
            read:projects: Read projects
            write:projects: Update projects
            read:employees: Read employees
            write:employees: Update employees
            read:allocations: Read allocations
            write:allocations: Update allocations
            read:history: Read history
            write:history: Update history
            read:feedback: Read feedback
            write:feedback: Update feedback
            read:settings: Read settings
            write:settings: Write settings
